package key

import (
	"fmt"
	"strings"
	"time"

	"github.com/gravitational/teleport/api/types"
)

const (
	AppOperatorVersion              = "0.0.0"
	TeleportOperatorFinalizer       = "teleport.finalizer.giantswarm.io"
	TeleportKubeAppDefaultNamespace = "giantswarm"
	TeleportKubeAppNamespace        = "kube-system"
	TeleportOperatorLabelValue      = "teleport-operator"
	TeleportOperatorConfigName      = "teleport-operator"
	TeleportBotSecretName           = "identity-output"
	TeleportBotNamespace            = "giantswarm"
	TeleportBotAppName              = "teleport-tbot"
	// TeleportKubeTokenValidity is the TTL for all join tokens generated by this
	// operator. Reduced from 720h to 1h to limit the blast radius of a leaked token.
	// Tokens are renewed proactively via TokenRenewalThreshold before they expire.
	TeleportKubeTokenValidity = 1 * time.Hour
	// TokenRenewalThreshold is how early before expiry a token is treated as invalid
	// and proactively rotated, ensuring agents always receive a token with sufficient
	// remaining validity and closing the window during which a stolen token is usable.
	TokenRenewalThreshold = 30 * time.Minute

	AppCatalog            = "appCatalog"
	AppName               = "appName"
	AppVersion            = "appVersion"
	IdentityFile          = "identityFile"
	Identity              = "identity"
	ManagementClusterName = "managementClusterName"
	ProxyAddr             = "proxyAddr"
	TeleportVersion       = "teleportVersion"
	RoleKube              = "kube"
	RoleApp               = "app"
	RoleNode              = "node"
)

func ParseRoles(s string) ([]string, error) {
	parts := strings.Split(s, ",")
	roles := make([]string, 0, len(parts))
	for _, part := range parts {
		part = strings.TrimSpace(part)
		switch part {
		case RoleKube, RoleApp, RoleNode:
			roles = append(roles, part)
		default:
			return nil, fmt.Errorf("invalid role: %s", part)
		}
	}
	return roles, nil
}

func RolesToString(roles []string) string {
	return strings.Join(roles, ",")
}

func RolesToSystemRoles(roles []string) []types.SystemRole {
	systemRoles := make([]types.SystemRole, 0, len(roles))
	for _, role := range roles {
		switch role {
		case RoleKube:
			systemRoles = append(systemRoles, types.RoleKube)
		case RoleApp:
			systemRoles = append(systemRoles, types.RoleApp)
		case RoleNode:
			systemRoles = append(systemRoles, types.RoleNode)
		}
	}
	return systemRoles
}

func GetConfigmapName(clusterName string, appName string) string {
	return fmt.Sprintf("%s-%s-config", clusterName, appName)
}

func GetTbotConfigmapName(clusterName string) string {
	return fmt.Sprintf("teleport-tbot-%s-config", clusterName)
}

func GetSecretName(clusterName string) string {
	return fmt.Sprintf("%s-teleport-join-token", clusterName)
}

func GetKubeconfigSecretName(clusterName string) string {
	return fmt.Sprintf("teleport-%s-kubeconfig", clusterName)
}

// GetRegisterName returns the Teleport register name for a cluster.
// When clusterUID is provided (non-empty), the first 8 characters are appended
// to make the name unique across cluster re-creations with the same name.
// An empty clusterUID falls back to the legacy two-component format to preserve
// backwards compatibility with already-registered clusters.
func GetRegisterName(managementClusterName, clusterName, clusterUID string) string {
	if clusterUID == "" {
		// Migration path: existing clusters that do not yet have a UID tracked
		// continue to use the old format to avoid re-registration churn.
		return fmt.Sprintf("%s-%s", managementClusterName, clusterName)
	}
	// Guard against unexpectedly short UIDs (real Kubernetes UIDs are 36-char UUIDs).
	shortUID := clusterUID
	if len(shortUID) > 8 {
		shortUID = shortUID[:8]
	}
	return fmt.Sprintf("%s-%s-%s", managementClusterName, clusterName, shortUID)
}

func GetAppSpecKubeConfigSecretName(clusterName string) string {
	return fmt.Sprintf("%s-kubeconfig", clusterName)
}

func GetAppName(clusterName string, appName string) string {
	return fmt.Sprintf("%s-%s", clusterName, appName)
}

func GetConfigmapDataFromTemplate(authToken string, proxyAddr string, kubeClusterName string, teleportVersion string, roles []string) string {
	dataTpl := `roles: "%s"
authToken: "%s"
proxyAddr: "%s"
kubeClusterName: "%s"
`

	if teleportVersion != "" {
		dataTpl = fmt.Sprintf("%steleportVersionOverride: %q", dataTpl, teleportVersion)
	}

	return fmt.Sprintf(dataTpl, RolesToString(roles), authToken, proxyAddr, kubeClusterName)
}

func GetTbotConfigmapDataFromTemplate(kubeClusterName string, clusterName string) string {
	dataTpl := `outputs:
  %s: "%s"
`

	return fmt.Sprintf(dataTpl, kubeClusterName, clusterName)
}
