version: 2.1

orbs:
  architect: giantswarm/architect@4.33.0

workflows:
  build:
    jobs:
      - architect/go-build:
          name: go-build
          binary: teleport-operator
          resource_class: large
          filters:
            tags:
              only: /^v.*/

      - architect/push-to-docker:
          context: "architect"
          name: push-teleport-operator-to-quay
          image: "quay.io/giantswarm/teleport-operator"
          username_envar: "QUAY_USERNAME"
          password_envar: "QUAY_PASSWORD"
          requires:
            - go-build
          # Needed to trigger job also on git tag.
          filters:
            tags:
              only: /^v.*/
      - architect/push-to-docker:
          context: "architect"
          name: push-teleport-operator-to-docker
          image: "docker.io/giantswarm/teleport-operator"
          username_envar: "DOCKER_USERNAME"
          password_envar: "DOCKER_PASSWORD"
          requires:
            - go-build
          # Needed to trigger job also on git tag.
          filters:
            tags:
              only: /^v.*/

      - architect/push-to-app-catalog:
          context: "architect"
          executor: "app-build-suite" # uncomment this if you want automatic metadata generation and helm chart linting
          name: push-teleport-operator-to-app-catalog
          app_catalog: "control-plane-catalog"
          app_catalog_test: "control-plane-test-catalog"
          chart: "teleport-operator"
          requires:
            - push-teleport-operator-to-quay
            - push-teleport-operator-to-docker
          # Needed to trigger job also on git tag.
          filters:
            tags:
              only: /^v.*/

      - architect/push-to-app-collection:
          name: aws-app-collection
          context: "architect"
          app_name: "teleport-operator"
          app_namespace: "giantswarm"
          app_collection_repo: "aws-app-collection"
          requires:
            - push-teleport-operator-to-quay
            - push-teleport-operator-to-docker
            - push-teleport-operator-to-app-catalog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/

      - architect/push-to-app-collection:
          context: architect
          name: push-to-capa-app-collection
          app_name: "teleport-operator"
          app_collection_repo: "capa-app-collection"
          requires:
            - push-teleport-operator-to-quay
            - push-teleport-operator-to-docker
            - push-teleport-operator-to-app-catalog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/

      - architect/push-to-app-collection:
          context: architect
          name: push-to-cloud-director-app-collection
          app_name: "teleport-operator"
          app_collection_repo: "cloud-director-app-collection"
          requires:
            - push-teleport-operator-to-quay
            - push-teleport-operator-to-docker
            - push-teleport-operator-to-app-catalog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/

      - architect/push-to-app-collection:
          context: architect
          name: push-to-capz-app-collection
          app_name: "teleport-operator"
          app_collection_repo: "capz-app-collection"
          requires:
            - push-teleport-operator-to-quay
            - push-teleport-operator-to-docker
            - push-teleport-operator-to-app-catalog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/

      - architect/push-to-app-collection:
          context: architect
          name: push-to-gcp-app-collection
          app_name: "teleport-operator"
          app_collection_repo: "gcp-app-collection"
          requires:
            - push-teleport-operator-to-quay
            - push-teleport-operator-to-docker
            - push-teleport-operator-to-app-catalog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/

      - architect/push-to-app-collection:
          context: architect
          name: push-to-vsphere-app-collection
          app_name: "teleport-operator"
          app_collection_repo: "vsphere-app-collection"
          requires:
            - push-teleport-operator-to-quay
            - push-teleport-operator-to-docker
            - push-teleport-operator-to-app-catalog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
