global:
  podSecurityStandards:
    enforced: false

ciliumNetworkPolicy:
  enabled: false

image:
  name: "giantswarm/teleport-operator"
registry:
  domain: gsoci.azurecr.io

teleport:
  appCatalog: giantswarm
  appName: teleport-kube-agent
  appVersion: 0.3.0
  managementClusterName: ""
  proxyAddr: test.teleport.giantswarm.io:443
  teleportClusterName: test.teleport.giantswarm.io
  teleportVersion: 16.1.7


pod:
  user:
    id: 1000
  group:
    id: 1000

resources:
  limits:
    cpu: 250m
    memory: 500Mi
  requests:
    cpu: 100m
    memory: 250Mi

# Add seccomp to pod security context
podSecurityContext:
  seccompProfile:
    type: RuntimeDefault
  runAsNonRoot: true

# Add seccomp to container security context
containerSecurityContext:
  readOnlyRootFilesystem: true
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL

tolerations:
  - effect: "NoSchedule"
    key: "node-role.kubernetes.io/control-plane"
  - effect: "NoSchedule"
    key: "node.cluster.x-k8s.io/uninitialized"
    operator: "Exists"

affinity:
  nodeAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
    - weight: 10
      preference:
        matchExpressions:
        - key: "node-role.kubernetes.io/control-plane"
          operator: "Exists"

tbot:
  enabled: false
  deployment: true
