project:
  branch: "[[ .Branch ]]"
  commit: "[[ .SHA ]]"
image:
  name: "giantswarm/teleport-operator"
  tag: "[[ .Version ]]"
registry:
  domain: docker.io

teleport:
  appCatalog: giantswarm-playground-test
  appName: teleport-kube-agent
  appVersion: 0.1.0-9b59f0bf85e7314aa9820e247e0a3bef21ea02cc
  managementClusterName: ""
  proxyAddr: test.teleport.giantswarm.io:443
  teleportVersion: 13.1.5
  identityFile: ""

pod:
  user:
    id: 1000
  group:
    id: 1000

resources:
  limits:
    cpu: 250m
    memory: 500Mi
  requests:
    cpu: 100m
    memory: 250Mi

# Add seccomp to pod security context
podSecurityContext:
  seccompProfile:
    type: RuntimeDefault
  allowPrivilegeEscalation: false
  runAsNonRoot: true
  capabilities:
    drop:
      - ALL

# Add seccomp to container security context
securityContext:
  seccompProfile:
    type: RuntimeDefault
