global:
  podSecurityStandards:
    enforced: false

image:
  name: "giantswarm/teleport-operator"
registry:
  domain: docker.io

teleport:
  appCatalog: giantswarm
  appName: teleport-kube-agent
  appVersion: 0.3.0
  managementClusterName: ""
  proxyAddr: teleport.giantswarm.io:443
  teleportClusterName: teleport.giantswarm.io
  teleportVersion: 14.1.1

pod:
  user:
    id: 1000
  group:
    id: 1000

resources:
  limits:
    cpu: 250m
    memory: 500Mi
  requests:
    cpu: 100m
    memory: 250Mi

# Add seccomp to pod security context
podSecurityContext:
  seccompProfile:
    type: RuntimeDefault
  runAsNonRoot: true

# Add seccomp to container security context
containerSecurityContext:
  readOnlyRootFilesystem: true
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
