apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "resource.default.name" . }}
  namespace: {{ include "resource.default.namespace" . }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
type: Opaque
data:
  appCatalog: {{ .Values.teleport.appCatalog | b64enc | quote }}
  appName: {{ .Values.teleport.appName | b64enc | quote }}
  appVersion: {{ .Values.teleport.appVersion | b64enc | quote }}
  managementClusterName: {{ .Values.teleport.managementClusterName | b64enc | quote }}
  proxyAddr: {{ .Values.teleport.proxyAddr | b64enc | quote }}
  teleportVersion: {{ .Values.teleport.teleportVersion | b64enc | quote }}
