apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "resource.default.name" . }}
  namespace: {{ include "resource.default.namespace" . }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
type: Opaque
data:
  appCatalog: {{ .Values.teleport.appCatalog | quote }}
  appName: {{ .Values.teleport.appName | quote }}
  appVersion: {{ .Values.teleport.appVersion | quote }}
  managementClusterName: {{ .Values.teleport.managementClusterName | quote }}
  proxyAddr: {{ .Values.teleport.proxyAddr | quote }}
  teleportVersion: {{ .Values.teleport.teleportVersion | quote }}

  {{- if .Values.ciBot.enabled }}
  test.proxyAddr: {{ .Values.ciBot.proxyAddr | quote }}
  test.managementClusterName: {{ .Values.ciBot.managementClusterName | quote }}
  test.teleportVersion: {{ default .Values.teleport.teleportVersion .Values.ciBot.teleportVersion | quote }}
  {{- end }}