
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "resource.default.name"  . }}
  namespace: {{ include "resource.default.namespace"  . }}
  labels:
  {{- include "labels.common" . | nindent 4 }}
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      {{- include "labels.selector" . | nindent 6 }}
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        releaseRevision: {{ .Release.Revision | quote }}
      labels:
        {{- include "labels.selector" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "resource.default.name" . }}
      securityContext:
        runAsUser: {{ .Values.pod.user.id }}
        runAsGroup: {{ .Values.pod.group.id }}
        {{- with .Values.podSecurityContext }}
          {{- . | toYaml | nindent 8 }}
        {{- end }}
      containers:
      - name: {{ .Chart.Name }}
        env:
        - name: TELEPORT_TLS_ROUTING_CONN_UPGRADE
          value: "{{ .Values.teleport.proxyAddr }}=yes"
        - name: USE_COMBINED_TOKENS
          value: {{ .Values.teleportOperator.useCombinedTokens | quote }}
        image: "{{ .Values.registry.domain }}/{{ .Values.image.name }}:{{ .Chart.Version }}"
        args:
        - "--namespace={{ include "resource.default.namespace" . }}"
        - "--roles={{ .Values.teleportOperator.roles | join "," }}"
        {{- if .Values.tbot.enabled }}
        - "--tbot"
        {{- end }}
        ports:
        - name: metrics
          protocol: TCP
          containerPort: 8080
        securityContext:
          {{- with .Values.containerSecurityContext }}
            {{- . | toYaml | nindent 10 }}
          {{- end }}
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
      terminationGracePeriodSeconds: 10
      affinity:
        {{- toYaml .Values.affinity | nindent 8 }}
      tolerations:
        {{- toYaml .Values.tolerations | nindent 8 }}
