apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: tbot-secrets-admin
  namespace: {{ include "resource.default.namespace"  . }}
  labels:
  {{- include "labels.common" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tbot-secrets-admin
  namespace: {{ include "resource.default.namespace"  . }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: tbot
roleRef:
  kind: Role
  name:  tbot-secrets-admin
  apiGroup: rbac.authorization.k8s.io
